[project]
name = "llm-with-examples"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "openai>=1.93.2",
    "pydantic>=2.11.7",
]
